version: '3.7'
volumes:
    dados:
networks: 
    banco:
    web:
    fila:
services:
    postgres-db:
        image: postgres:12.2
        container_name: postgres-db
        hostname: postgres-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            # Volume dos dados
            - dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks: 
            - banco
    proxy:
        image: nginx:1.17.9
        container_name: proxy
        hostname: proxy
        volumes:
            # Site
            - ./web:/usr/share/nginx/html/
            # Configuração do proxy reverso
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks: 
            - web
        depends_on: 
            - app
    app:
        image: python:3.6
        volumes:
            # Aplicação
            - ./app:/app
        working_dir: /app
        command: bash ./app.sh
        networks: 
            - banco
            - web
            - fila
        depends_on: 
            - postgres-db
            - queue
    queue:
        image: redis:6.0-rc
        networks: 
            - fila
    worker:
        image: python:3.6
        volumes: 
            - ./worker:/worker
        working_dir: /worker
        command: bash ./app.sh
        networks: 
            - fila
        depends_on: 
            - queue