---
version: '3.7'
volumes:
    dados:
networks: 
    database:
    web:
    queue:
services:
    postgres-db:
        image: postgres:12.2
        container_name: postgres-db
        hostname: postgres-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            # Database volume
            - ./dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks: 
            - database
    proxy:
        image: nginx:1.17.9
        container_name: proxy
        hostname: proxy
        volumes:
            # Site
            - ./web:/usr/share/nginx/html/
            # Reverse prroxy conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks: 
            - web
        depends_on: 
            - app
    app:
        image: python:3.6
        container_name: app
        hostname: app
        volumes:
            # Application
            - ./app:/app
        working_dir: /app
        command: bash ./app.sh
        networks: 
            - database
            - web
            - queue
        depends_on: 
            - postgres-db
            - queue
    queue:
        image: redis:6.0-rc
        container_name: queue-agent
        hostname: queue-agent
        networks: 
            - queue
    worker:
        build: worker
        volumes: 
            - ./worker:/worker
        working_dir: /worker
        command: worker.py
        networks: 
            - queue
        depends_on: 
            - queue
...